name: Deploy frontend to dev

on:
  workflow_dispatch:

jobs:
  frontend_deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build the app
        run: npm run build
        working-directory: frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::905418140364:role/github-action-deployment-role
          role-session-name: samplerolesession
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/dist/therix-frontend/ s3://therix-frontend-test